name: Run Python Tests

on:
  push:
    branches:
      - '**'   # Run on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Run tests
        if: startsWith(github.event_name, 'push') && startsWith(github.ref, 'refs/heads/feature/')
        run: |
          python tests/*.py
        if: steps.run.outputs.result == 'success'
        - name: Create PR
          uses: actions/github-script@v6
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR_TITLE: 'Test passed'
            PR_BODY: 'Test passed'
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const pr = await github.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: process.env.PR_TITLE,
                body: process.env.PR_BODY,
                head: context.payload.pull_request.head.ref,
                base: 'test'
              })
              core.info(`PR created: ${pr.data.html_url}`)
