name: Run Python Tests

on:
  push:
    branches:
      - '**'   # Run on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Run tests
        if: startsWith(github.ref_name, 'feature/')
        run: |
          python tests/example_feature_test.py
          python tests/main_test.py

      - name: Create PR
        if: ${{ success() }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR using GitHub CLI
        if: ${{ success() }}
        run: |
          gh pr create --title "Test passed" --body "All tests passed successfully" --base main --head ${{ github.ref_name }}
